import logging
import pickle
import random
import sys
import warnings

import numpy as np
import pandas as pd
import scipy
from scipy.stats import norm
from sklearn.preprocessing import LabelEncoder

from sdgx.data_loader import DataLoader
from sdgx.data_models.metadata import Metadata
from sdgx.models.base import SynthesizerModel

LOGGER = logging.getLogger(__name__)


def get_nearest_correlation_matrix(matrix):
    """Find the nearest correlation matrix.

    If the given matrix is not Positive Semi-definite, which means
    that any of its eigenvalues is negative, find the nearest PSD matrix
    by setting the negative eigenvalues to 0 and rebuilding the matrix
    from the same eigenvectors and the modified eigenvalues.

    After this, the matrix will be PSD but may not have 1s in the diagonal,
    so the diagonal is replaced by 1s and then the PSD condition of the
    matrix is validated again, repeating the process until the built matrix
    contains 1s in all the diagonal and is PSD.

    After 10 iterations, the last step is skipped and the current PSD matrix
    is returned even if it does not have all 1s in the diagonal.

    Insipired by: https://stackoverflow.com/a/63131250
    """
    eigenvalues, eigenvectors = scipy.linalg.eigh(matrix)
    negative = eigenvalues < 0
    identity = np.identity(len(matrix))

    for iterations in range(10):
        if not np.any(negative):
            break
        eigenvalues[negative] = 0
        matrix = eigenvectors.dot(np.diag(eigenvalues)).dot(eigenvectors.T)

        matrix = matrix - matrix * identity + identity

        max_value = np.abs(np.abs(matrix).max())
        if max_value > 1:
            matrix /= max_value

        eigenvalues, eigenvectors = scipy.linalg.eigh(matrix)
        negative = eigenvalues < 0

    return matrix


class TabCopSynthesizerModel(SynthesizerModel):
    """TabCop is a synthetic data generation model based on the Gaussian copula. It simultaneously achieves low computational complexity, competitive performance, and privacy.

    By introducing a cumulative frequency table, TabCop accurately characterizes the distribution of each column of real data. Consequently, the columns of the synthetic data generated by TabCop can follow the same distributions as the columns of real data.

    To better protect data privacy, TabCop uses differential privacy while maintaining the computational and performance advantages.

    Args:
        t (int):
            The number of the interval in the frequency distribution table. Defaults to ``100``.
        g (int):
            The number of the interval in the inverse cumulative frequency table. Defaults to ``100``.
        epsilon (float):
            The privacy budget of Differential Privacy. It should be a positive value or ``None``. TabCop will not use differential privacy if it is set to ``None``. Defaults to ``None``.
    """

    def __init__(
        self,
        t=100,
        g=100,
        epsilon=None,
    ):
        self.encoder_list = {}
        self.col_names = []
        self.nan_cols = []
        self.dtypes = {}
        self.nan_columns_min = {}
        self.dtype_int = []
        self.discrete_columns = []
        self.cdf_tables = []
        self.corration = 0
        self.mean = 0
        self.t = t
        self.g = g
        self.epsilon = epsilon

    def fit(self, metadata: Metadata, dataloader: DataLoader, *args, **kwargs):
        """Fit the model based on the provided data.

        Args:
            metadata (Metadata): The metadata associated with the raw data.
            dataloader (DataLoader): The dataloader used to extract the raw data to fit the model.

        Returns:
            None
        """

        transform_data = []

        # extract pd.DataFrame processed_data from dataloader
        data: pd.DataFrame = dataloader.load_all()

        # get discrete_columns from metadata
        self.discrete_columns = list(metadata.get("discrete_columns"))

        self.col_names = list(metadata.get("column_list"))

        # Column data pre-processing
        for column_name in data.columns:
            if data[column_name].dtype == "object":
                le = LabelEncoder()
                le.fit(data[column_name].values.astype(str))
                self.encoder_list[column_name] = le
            raw_column_data = data[column_name].values
            if column_name in self.discrete_columns:
                transform_column_data = (
                    self.encoder_list[column_name]
                    .transform(raw_column_data.astype(str))
                    .astype("float32")
                )
                self.dtypes[column_name] = str(transform_column_data.dtype)
            else:
                self.dtypes[column_name] = str(raw_column_data.dtype)
                no_nan = (1 - np.isnan(raw_column_data)).astype("bool")
                int_raw_column_data = raw_column_data[no_nan].astype("int32")
                if (int_raw_column_data == raw_column_data[no_nan]).sum() == len(
                    raw_column_data[no_nan]
                ):
                    self.dtype_int.append(column_name)
                if pd.isna(raw_column_data).sum() > 0:
                    self.nan_columns_min[column_name] = np.nanmin(raw_column_data)
                    raw_column_data[pd.isna(raw_column_data)] = np.nanmin(raw_column_data) - 1
                    self.nan_cols.append(column_name)
                transform_column_data = raw_column_data
            transform_data.append(transform_column_data)
        X = np.array(transform_data).T

        transform_X = []

        # Compute the cumulative distribution table and transform the column data to the data following Gaussian distribution
        for i in range(X.shape[1]):
            transform_column = []
            cdf_table = {}
            min_value = X[:, i].min()
            max_value = X[:, i].max()
            if self.epsilon != None:
                f = lambda x: x + np.random.laplace(loc=0, scale=1 / (self.epsilon / 10))
                column_count = pd.Series(X[:, i]).value_counts()
                min_counts = column_count.sort_index(ascending=False)
                max_counts = column_count.sort_index(ascending=True)
                min_counts = min_counts.cumsum() - min_counts.values
                min_counts = min_counts.apply(f)
                min_value = min_counts.index[min_counts.argmax()]
                max_counts = max_counts.cumsum() - max_counts.values
                max_counts = max_counts.apply(f)
                max_value = max_counts.index[max_counts.argmax()]
                if min_value >= max_value:
                    max_value = min_value + 1e-6
            n, bins = np.histogram(X[:, i], self.t, (min_value, max_value), density=False)
            n = n.astype("float64")
            if self.epsilon != None:
                n += np.random.laplace(loc=0, scale=1 / (self.epsilon / 2), size=len(n))
            zero_index = np.argwhere(n <= 0).reshape(-1)
            n[zero_index] = 1e-6
            n /= n.sum()
            n = np.cumsum(n)
            cdf_table["data"] = bins
            cdf_table["cdf"] = n
            self.cdf_tables.append(cdf_table)

            n[-1] -= 1e-6
            transform_X.append(
                norm.ppf(
                    n[
                        np.floor(
                            self.t
                            * (X[:, i] - X[:, i].min())
                            / (X[:, i].max() + 1e-6 - X[:, i].min())
                        ).astype("int32")
                    ],
                    0.0,
                    1.0,
                )
            )
            n[-1] += 1e-6
        transform_X = np.array(transform_X).T

        # Compute covariance
        dt = pd.DataFrame(transform_X)
        corration = dt.cov().values.astype(np.float32)
        corration = np.nan_to_num(corration, nan=0.0)
        if self.epsilon != None:
            corration += np.random.laplace(
                loc=0,
                scale=2 * corration.shape[1] / (3 * self.epsilon / 10),
                size=(corration.shape[0], corration.shape[1]),
            )

        # If singular, add some noise to the diagonal
        if np.linalg.cond(corration) > 1.0 / sys.float_info.epsilon:
            corration = corration + np.identity(corration.shape[0]) * 1e-6
        self.corration = get_nearest_correlation_matrix(corration)
        self.mean = transform_X.mean(axis=0)

    def sample(self, num_rows):
        """Sample the indicated number of rows from the model.

        Args:
            num_rows (int):
                Amount of rows to sample.

        Returns:
            pandas.DataFrame:
                Sampled data.
        """
        Y = np.random.multivariate_normal(self.mean, self.corration, num_rows)

        tables = []
        new_data = []

        # Compute the inverse cumulative distribution table and transform the data that follow Gaussian distribution based on the inverse cumulative distribution table
        for i in range(len(self.col_names)):
            table = []
            bins = self.cdf_tables[i]["data"]
            n = self.cdf_tables[i]["cdf"]
            n = np.around(n, 5)
            old = 0
            table.append([bins[0], bins[1]])
            for j in range(len(n)):
                if n[j] == old:
                    continue
                for k in range(int(old * self.g) + 1, int(n[j] * self.g) + 1):
                    table.append([bins[j], bins[j + 1]])
                old = n[j]
            tables.append(table)
            cdf = norm.cdf(Y[:, i], Y[:, i].mean(), Y[:, i].std())
            values = []
            cdf = np.around(cdf, 5)
            for item in cdf:
                values.append(
                    random.uniform(table[int(item * self.g)][0], table[int(item * self.g)][1])
                )
            values = np.array(values)
            new_data.append(values)
        new_data = np.array(new_data).T
        sys_data = pd.DataFrame(new_data, columns=self.col_names)

        # Synthetic column data post-processing
        for column_name in sys_data.columns:
            if column_name in self.discrete_columns:
                sys_data[column_name] = pd.Series(
                    self.encoder_list[column_name].inverse_transform(
                        np.around(sys_data[column_name]).astype("int32")
                    ),
                    index=sys_data[column_name].index,
                )
                sys_data.loc[sys_data[column_name] == "nan", column_name] = np.nan
                sys_data[column_name] = sys_data[column_name].astype("object")
            else:
                if column_name in self.dtype_int:
                    sys_data[column_name] = np.around(
                        sys_data[column_name].astype("float64")
                    ).astype(self.dtypes[column_name])
                else:
                    sys_data[column_name] = sys_data[column_name].astype(self.dtypes[column_name])
                if column_name in self.nan_cols:
                    sys_data.loc[
                        sys_data[column_name] < self.nan_columns_min[column_name], column_name
                    ] = np.nan
        return sys_data

    @classmethod
    def load(cls, path):
        f = open(path, "rb")
        parameters = pickle.load(f)
        f.close()
        model = TabCopSynthesizerModel(
            t=parameters["t"], g=parameters["g"], epsilon=parameters["epsilon"]
        )
        model.encoder_list = parameters["encoder_list"]
        model.col_names = parameters["col_names"]
        model.nan_cols = parameters["nan_cols"]
        model.dtypes = parameters["dtypes"]
        model.nan_columns_min = parameters["nan_columns_min"]
        model.dtype_int = parameters["dtype_int"]
        model.discrete_columns = parameters["discrete_columns"]
        model.cdf_tables = parameters["cdf_tables"]
        model.corration = parameters["corration"]
        model.mean = parameters["mean"]
        return model

    def save(self, path):
        model = {}
        model["encoder_list"] = self.encoder_list
        model["col_names"] = self.col_names
        model["nan_cols"] = self.nan_cols
        model["dtypes"] = self.dtypes
        model["nan_columns_min"] = self.nan_columns_min
        model["dtype_int"] = self.dtype_int
        model["discrete_columns"] = self.discrete_columns
        model["cdf_tables"] = self.cdf_tables
        model["corration"] = self.corration
        model["mean"] = self.mean
        model["t"] = self.t
        model["g"] = self.g
        model["epsilon"] = self.epsilon
        f = open(path, "wb")
        pickle.dump(model, f)
        f.close()
