name: Testing example extensions

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]
      - name: Install all packages in example/extension
        run: |
          python -m pip install -e example/extension/dummymetadatainspector[test]
          python -m pip install -e example/extension/dummycache[test]
          python -m pip install -e example/extension/dummydataconnector[test]
          python -m pip install -e example/extension/dummydataprocessor[test]
          python -m pip install -e example/extension/dummymodel[test]
      - name: Test with pytest
        run: |
          pytest -vv example/extension
