name: GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the new step to run the necessary actions and capture error logs
      - name: Run Actions and Capture Error Logs
        run: |
          # Add the necessary commands to run the actions and capture error logs

          # Example command to run actions and capture error logs
          echo "Running actions..."
          ./run_actions.sh 2> error_logs.txt
          pytest -vv --cov-config=.coveragerc --cov=sdgx/ tests

      # Add any other existing steps
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # The token is required and should be stored as a GitHub secret
          file: coverage.xml # The path to the coverage report file
          fail_ci_if_error: true
          flags: appropriate_categorization # Optional, you can use this to categorize coverage reports
          name: meaningful_workflow_name # Optional, you can use this to provide a name for the workflow
          fail_ci_if_error: true # Optional, if set to true, the workflow will fail if the step fails
